### ISSUE TITLE
/instance/connect/{Instance} não retorna QRCode 

### ISSUE THREAD

**Issue by lucianosg** [code-chat-br/whatsapp-api#105]
A requisição "/instance/connect/{Instance}" não está retornando o QRCode.

{
   originalUrl: '/instance/connect/wapi_v13020_34',
   method: 'GET',
   headers: '{"connection":"Keep-Alive",
              "content-type":"application/json",
			  "accept-charset":"utf-8",
			  "host":"http://192.168.0.5:8082",
			  "user-agent":"Embarcadero URI Client/1.0",
			  "apikey":"YzYzP7ocstxh3SJ23D4FZTCu4ehnM8v4huY"}',
   params: '{"instanceName":"wapi_v13020_34"}',
   query: '{}',
   body: '{}'
 }

A resposta que esta retornando:

{
	"count": 1
}

Porém o QRCode é exibido no terminal e é retornado através de WebHooks. 
Executei o teste em várias versões e o resultado foi o mesmo.

**Comment by jrCleber** [comment]
Possivelmente a requisição está sendo finalizada antes das variáveis serem carregadas.
Faça seguinte: quando retorna somente o count, chame novamente esse endpoint, imediatamente após o retorno e me dá o feedback aqui.

(Pode ser que o seu servidor processe a conexão com o whatsapp um pouco mais lento)
