### ISSUE TITLE
Unable to send messages to numbers from mexico +521

### ISSUE THREAD

**Issue by saadnust** [code-chat-br/whatsapp-api#107]
For numbers of format `521`, even if the number exists on the whatsapp, response is showing `exists:False`

**Comment by jrCleber** [comment]
In Brazil, there are specific rules for telephone operator numbers that are implemented in the code.

In Mexico there are also these rules, but I don't know them. If you know these rules well, make a pull request and I will review and accept it.

**Comment by salomonamiga** [comment]
For Mexico you only have to remove the 1
