### ISSUE TITLE
findChats | findContacts issue

### ISSUE THREAD

**Issue by mrlazarias** [code-chat-br/whatsapp-api#113]
I'm trying to retrieve the list of chats I have on WhatsApp. I think I need to fetch it from the findChats endpoint and then, using the RemoteJid, make another request to findContacts. However, the response I'm getting is completely unexpected. I'm receiving a list of several objects with the same RemoteJid, and these objects also have pushName as null.

How can I fetch the chats and the contact information for each chat to build the list of active chats?

**Comment by jrCleber** [comment]
Esse comportamento ainda persiste?

**Comment by mrlazarias** [comment]
Sim

> Esse comportamento ainda persiste?

**Comment by jrCleber** [comment]
Esse comportamento é bem incomum. Delete esses contatos e se reconecta.
Informe aqui se o erro ainda persiste.
