### ISSUE TITLE
Contacts limit ( findContacts )

### ISSUE THREAD

**Issue by Pedro-Coimbra** [code-chat-br/whatsapp-api#114]
Im trying to retrieve my list of contacts but its seems to have a limit of 6000 contacts, there is way that i can surpass this limit or a pagination option?

**Comment by jrCleber** [comment]
É uma lista bem grande mesmo. Nesse caso seria apropriado retornar esses dados como stream. Mas a api não faz essa transformação. Sugiro que você crie a sua própria lógica para lidar com essa quantidade de dados.
