### ISSUE TITLE
Empty messages are getting delivered to the groups in spite of a text message being added. This happens randomly.

### ISSUE THREAD

**Issue by aravindanf22labs** [code-chat-br/whatsapp-api#116]
<img width="417" alt="Screenshot 2024-03-26 at 4 39 45 PM" src="https://github.com/code-chat-br/whatsapp-api/assets/47236422/b5cc726e-8469-4a16-a274-8526a496a536">

**Comment by jrCleber** [comment]
What is your API version?
Is the `body` of the request correct?

**Comment by Pedro-Coimbra** [comment]
Im having the same problem in version 1.2.8

**Comment by jrCleber** [comment]
> Im having the same problem in version 1.2.8

Que tipo de mensagem você está tentando enviar?

**Comment by Pedro-Coimbra** [comment]
Aconteceu comigo com mensagem de texto normal,  é  meio aleatório que nem o cara disse, teve mensagem que não chegou aí eu copiei e colei a mesma mensagem pra tentar debugar e pegar um possível erro mas a mensagem chegou.

**Comment by aravindanf22labs** [comment]
@jrCleber I am using version 1.2.8. And yes, the request body sent is correct.
