### ISSUE TITLE
Messages only arriving in Whatsapp Windows installation

### ISSUE THREAD

**Issue by gutodiasdev** [code-chat-br/whatsapp-api#117]
Hi, i'm using N8N to send a message with image and caption to a number list. But the message only arrives in Whatsapp Windows.

**API version: 1.3**

Anyone know how to solve the problem and show the messages in all devices?

**Comment by jrCleber** [comment]
The body of your request is probably incorrect.
Are you passing the correct `mediatype`?
Does the media `url` contain the file extension? If not, enter the `fileName`.

**Comment by jrCleber** [comment]
Entendi!

Isso tem a ver com o `mimetype` do arquivo; a aplicação não está identificando corretamente se é uma imagem, ou um vídeo, ou um arquivo, etc.

Isso ocorre porque na `url` da mídia não contém a extensão do arquivo; se é `.png`, ou `.webp`, ou `jpg`, etc.

```ts
{
  mediatype: "image",
  caption: "string",
  media: "...cloudfront.net/user_2eBgK1j4GtX4yWVBmpcdpQKyBZ8/1711625204317_image"
}
```

No corpo da requisição informe o `filename`, [por exemplo](https://www.postman.com/codechat/workspace/codechat-whatsapp-api/request/14064846-852fbd90-cc26-4563-ae69-daf1df15ba9a?tab=body):

```ts
{
  mediatype: "image",
  caption: "string",
  filename: "1711625204317_image.png",
  media: "...cloudfront.net/user_2eBgK1j4GtX4yWVBmpcdpQKyBZ8/1711625204317_image"
}
```

**Comment by gutodiasdev** [comment]
Funcionou!

Não utilizei o filename, pra funcionar direitinho eu preciso instalar o sharp no pra garantir a conversão do buffer e apenas indiquei , e adicionei a extensão .jpg na criação dos links.

Muito obrigado, @jrCleber.
