### ISSUE TITLE
not returning qrcode

### ISSUE THREAD

**Issue by Saifallak** [code-chat-br/whatsapp-api#118]
![image](https://github.com/code-chat-br/whatsapp-api/assets/6053156/9ca9806c-72f3-4180-a384-06b3f1ab27d7)

**Comment by jrCleber** [comment]
Was there already a connection to this instance?

**Comment by Saifallak** [comment]
Latest commit on main branch
Nope not connected and fresh install

**Comment by jrCleber** [comment]
OK!
Make the request directly via postman and check if you get the same error:

* [Collection V1.3](https://www.postman.com/codechat/workspace/codechat-whatsapp-api/collection/14064846-194eec6c-c3d6-48d1-9660-93d8085fd83a)
* [Connect](https://www.postman.com/codechat/workspace/codechat-whatsapp-api/example/14064846-359634aa-69c5-4260-b01b-bf9eb5586b1f)
* [View Qrcode](https://www.postman.com/codechat/workspace/codechat-whatsapp-api/request/14064846-d81814af-0e76-4d18-b3c6-32e237609b96)

**Comment by rodrigocabraln** [comment]
I think WhatsApp made some changes, I have the same problem with another project

**Comment by jrCleber** [comment]
Tentei replicar esse problema aqui, mas obtive sucesso em todas as vezes.

![image](https://github.com/code-chat-br/whatsapp-api/assets/65574896/963e7fae-4969-4970-8694-8b7dd8c8e2ac)

Mas, ainda assim fiz uma pequena alteração f70dbbf.
