### ISSUE TITLE
Apenas funcionando a rota: "instance/fetchInstances/"

### ISSUE THREAD

**Issue by gutodiasdev** [code-chat-br/whatsapp-api#120]
**Version: 1.3**

Olá, tudo bem? Está havendo um problema interessante.

![Screenshot_1](https://github.com/code-chat-br/whatsapp-api/assets/87369591/88c8fa15-fe5d-4886-a254-70075727ef00)

Eu consigo pegar as instâncias ativas da api, tudo funciona normal, porém, depois de um tempo ela começa a não reconhecer mais o id da instância. Informando que ela não existe ou não está conectada. Mas não é o caso.

![Screenshot_2](https://github.com/code-chat-br/whatsapp-api/assets/87369591/75274e5a-8244-4d6e-b870-11053a7cba27)

Desde já, agradeço.

**Comment by jrCleber** [comment]
Bom dia!
Uai!!!

Gerou algum erro no console?

**Comment by gutodiasdev** [comment]
Não gera erro no log:

![Screenshot_3](https://github.com/code-chat-br/whatsapp-api/assets/87369591/ea707f68-03ff-445d-93f1-0f6ce1cd6a4c)

Esse é o log onde a aplicação está, um exemplo que quando a aplicação diz que a instância não existe ou não está conectada. Um detalhe, a primeira que eu fiz, deu certo, retornou normalmente, fiz a segunda tentativa e já retornou 400.

**Comment by gutodiasdev** [comment]
> @gutodiasdev Toma cuidado com esses prints porque estão expondo os tokens de acesso da API, principalmente se eles são de produção.

Fato, não atentei, de qualquer forma, é um produção teste rs

**Comment by jrCleber** [comment]
> Não gera erro no log:
> 
> Esse é o log onde a aplicação está, um exemplo que quando a aplicação diz que a instância não existe ou não está conectada. Um detalhe, a primeira que eu fiz, deu certo, retornou normalmente, fiz a segunda tentativa e já retornou 400.
> 
> Tentei novamente e deu certo, depois não deu novamente. Ou seja, está intermitente.

Vou verificar isso.

**Comment by gutodiasdev** [comment]
Muito obrigado, se precisar de alguma coisa da minha parte fique a vontade pra solicitar.

**Comment by jrCleber** [comment]
Alguma atualização sobre esse erro?

**Comment by jrCleber** [comment]
Para novas questões, [reabra a sua issue](https://github.com/code-chat-br/whatsapp-api/issues/new?assignees=jrcleber&labels=bug%2Chelp+wanted&projects=&template=bug_report_br.yaml).
