### ISSUE TITLE
pushname in Messages table

### ISSUE THREAD

**Issue by mrlazarias** [code-chat-br/whatsapp-api#122]
Database Messages, the pushname is coming empty, did anyone manage to handle it?
![image](https://github.com/code-chat-br/whatsapp-api/assets/43286444/9998b071-ffd2-4732-9b7a-5f916521988e)

**Comment by jrCleber** [comment]
Esse **pushName** pode vir vazio sim quando os primeiros lotes de mensagens forem carregados, imediatamente após a leitura do qrcode.

Mas, farei um ajuste para o campo não ficar vazio.
