### ISSUE TITLE
keyParticipant vem nulo quando as mensagens são de grupos

### ISSUE THREAD

**Issue by lucasribeiro97** [code-chat-br/whatsapp-api#124]
![Captura de tela de 2024-05-08 16-49-23](https://github.com/code-chat-br/whatsapp-api/assets/76178670/f510875e-2492-4c5b-904a-e69c4fecadf4)

mesmo ja identificando que o campo foi enviado pelo dispostivo conectado (keyFromMe) ele como pode ver na imagem, o keyparticipant vem nulo, também reparei q isso ocorre nas mensagens mais recents no banco, as mais antigas aparentemente vem correto

**Comment by mrlazarias** [comment]
Estou com o mesmo problema

**Comment by jrCleber** [comment]
Isso será pontuado para análise e correção nesse fim de semana.

**Comment by jrCleber** [comment]
> ![Captura de tela de 2024-05-08 16-49-23](https://private-user-images.githubusercontent.com/76178670/329021107-f510875e-2492-4c5b-904a-e69c4fecadf4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwNjA5MTksIm5iZiI6MTcxNjA2MDYxOSwicGF0aCI6Ii83NjE3ODY3MC8zMjkwMjExMDctZjUxMDg3NWUtMjQ5Mi00YzViLTkwNGEtZTY5YzRmZWNhZGY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDE5MzAxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjYzZhYmI4OTliMjdlYWFkY2VhNjNjN2NjNWQwMTdiODUyNjgzYTFhZTAwOTlkNDQ4YTkxM2VhMzkwM2U1ZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Nfxnb5qSfA0Y_p8HASjXfB6zZG2plth6gF9NAubCgFY)
> 
> mesmo ja identificando que o campo foi enviado pelo dispostivo conectado (keyFromMe) ele como pode ver na imagem, o keyparticipant vem nulo, também reparei q isso ocorre nas mensagens mais recents no banco, as mais antigas aparentemente vem correto

Então, durante o carregamento dos lotes das mensagens, imediatamente a leitura do **qrcode**, esse campo pode vir vazio. Principalmente com mensagens muito antigas. Mas, farei um ajuste para minimizar isso.
