### ISSUE TITLE
Evento de Scaneamento de QRCode

### ISSUE THREAD

**Issue by Rafael-Floriano** [code-chat-br/whatsapp-api#125]
Gostaria de começar destacando a excelente qualidade da API!  parabéns a todos os envolvidos no projeto!

Estamos atualmente implementando a whatsapp-api e estamos enfrentando alguns desafios com o escaneamento do QR code. Basicamente, estamos procurando um evento que seja acionado quando o usuário faz o escaneamento do QR code, mostrando o número de telefone associado ao QR code escaneado. No momento, estamos utilizando o "connection.update", que é bastante útil para esse propósito, mas muitas vezes ele nos fornece o número de telefone desatualizado. Após revisar a documentação, não identificamos nenhum evento especificamente destinado ao escaneamento do QR code.

Além disso, o problema com o "connection.update" é que, como não foi desenvolvido para esse cenário específico, acaba gerando um processamento desnecessário em nosso caso. Na verdade, apenas precisamos saber quando o usuário faz o escaneamento do QR code e qual é o número de telefone associado a ele.

Gostaria de saber se seria possível um evento de webhook para esse cenário.

**Comment by jrCleber** [comment]
Para novas questões [reabra a issue aqui](https://github.com/code-chat-br/whatsapp-api/issues/new?assignees=jrcleber&labels=bug%2Chelp+wanted&projects=&template=bug_report_br.yaml).
