### ISSUE TITLE
Redis buscando todas as key

### ISSUE THREAD

**Issue by w3nder** [code-chat-br/whatsapp-api#14]
Acredito que o correto seria utilizar algum prefixo na consulta e criação das chave no redis.
https://github.com/code-chat-br/whatsapp-api/blob/main/src/db/redis.client.ts#L21

Se eu estiver usando o meu servidor de redis com o bull por exemplo que ele cria as chave bull: algo quando api e iniciada ele pega essa chave e cria uma conexão para ela. 

![image](https://user-images.githubusercontent.com/1123103/235677396-1d018f1c-10e5-4e58-a854-9f555f4affbf.png)

Então talvez seria interessante adicionar uma key para o tipo de conexão

**Comment by jrCleber** [comment]
Realmente! Irei realizar a sugestão.
Obrigado.
