### ISSUE TITLE
For a any event adhoc data that is sent in the request, must be received in the webhook callback.

### ISSUE THREAD

**Issue by aravindanf22labs** [code-chat-br/whatsapp-api#143]
We are unable to identify the internal resource from the Webhook data provided by codechat. We want certain data that will be part of the request, to be part of the Webhook data.

**Comment by jrCleber** [comment]
Format the data to base64 and add in the URL query in the webhook record.

**Comment by aravindanf22labs** [comment]
Let me elaborate on the requirement. 

When I send a text message, I receive message.update event with DELIVERY_ACK post delivery. When I make a request to send a message, I will send some additional data. I would need that data to be returned to me in the webhook callback.  

This would help me in identifying the resource that triggered the message. The data I send is dynamic that varies for each message wrt resource that triggered this event.
