### ISSUE TITLE
sendList não está funcionando

### ISSUE THREAD

**Issue by dnl4** [code-chat-br/whatsapp-api#144]
### Pesquisei problemas semelhantes no [GitHub](https://github.com/code-chat-br/whatsapp-api/issues) e não encontrei nenhum.

- [X] Sim

### Quais passos para chegar ao problema?

Chamei o endpoint: `http://localhost:8084/message/sendList/974494fc-a05c-409f-b462-135d248d9ebe`

```json
{
  "number": "[numero_aqui]",,
  "options": {
    "delay": 1200,
    "presence": "composing"
  },
  "listMessage": {
    "title": "1",
    "description": "2",
    "buttonText": "3",
    "footerText": "4",
    "sections": [
      {
        "title": "5",
        "buttonText": "6",
        "list": [{
          "rows": [{
            "title": "7",
            "description": "8",
            "rowId": "9"
          }]
      } ]
      }
    ]
  }
}
```

### Descreva o que você esperava que acontecesse.

Chegar no meu telefone uma "lista" que me permite selecionar entre algumas opções

### Explique o que realmente acontece quando você segue os passos acima.

No celular não chegou nada. 

Porém no computador (web whatsapp) chegou isso:

![image](https://github.com/user-attachments/assets/1e0e3a4a-64dd-47d0-8a03-23005f9e5e0a)

### Insira o número da sua versão que está na propriedade `version` do **package.json**.

codechat/api:latest

Package.json:
```
  "version": "1.3.2",
  ```

### Se possível, adicione capturas de tela ou vídeos que ilustrem o problema.
Isso pode ser extremamente útil para entender melhor o problema.

_No response_

### O ambiente no qual a aplicação está em execução

Docker

### Por favor, anexe os logs que possam estar relacionados ao problema.
Se os logs contiverem informações sensíveis, considere enviá-los de forma privada para um dos mantenedores do projeto.

_No response_

**Comment by jrCleber** [comment]
O dispositivo era **Android** ou **IOS**?

**Comment by dnl4** [comment]
@jrCleber , tanto o dispositivo que usei para escanear o qrcode, quanto o dispositivo que estava recebendo a mensagem , eram iOS

**Comment by jrCleber** [comment]
Botões não são 100% seguros.
Tente escanear novamente o qrcode, ou se conectar de com outro dispositivo.

**Comment by dnl4** [comment]
@jrCleber, poderia me informar em qual cenário ai do seu lado funcionou, para que eu possa replicar aqui?

**Comment by jrCleber** [comment]
Me conectei tanto com um Android, quanto com um IOS utilizando uma conta business.
