### ISSUE TITLE
Sendlist not found 

### ISSUE THREAD

**Issue by daniloreis88** [code-chat-br/whatsapp-api#152]
### Pesquisei problemas semelhantes no [GitHub](https://github.com/code-chat-br/whatsapp-api/issues) e não encontrei nenhum.

- [X] Sim

### Quais passos para chegar ao problema?

{{baseUrl}}/message/sendList/Instancia not found

### Descreva o que você esperava que acontecesse.

send list 

### Explique o que realmente acontece quando você segue os passos acima.

notwork

### Insira o número da sua versão que está na propriedade `version` do **package.json**.

1,3,3

### Se possível, adicione capturas de tela ou vídeos que ilustrem o problema.
Isso pode ser extremamente útil para entender melhor o problema.

_No response_

### O ambiente no qual a aplicação está em execução

Docker

### Por favor, anexe os logs que possam estar relacionados ao problema.
Se os logs contiverem informações sensíveis, considere enviá-los de forma privada para um dos mantenedores do projeto.

_No response_

**Comment by jrCleber** [comment]
Isso é comum. Listas e botões sempre são instáveis.

**Comment by daniloreis88** [comment]
show, entao no caso informa que nao foi encontrada , saiu da versao 1.3.3 ?

**Comment by jrCleber** [comment]
> show, entao no caso informa que nao foi encontrada , saiu da versao 1.3.3 ?

Como assim? "entao no caso informa que nao foi encontrada"

--- 
"saiu da versao 1.3.3 ?"
Não saiu da versão 1.3.3. 
Pode ser alguma incompatibilidade com o seu número, ou a versão do whatsapp.
Ou a versão da baileys instalada não consegue enviar.

**Comment by daniloreis88** [comment]
Isso mesmo quando executo o post desse informa q  notFound 404

**Comment by daniloreis88** [comment]
Fiz a instalação pelo docker

**Comment by jrCleber** [comment]
Está usando esta [collection](https://www.postman.com/codechat/workspace/codechat-api/collection/14064846-fb3668d9-d976-45d6-92f7-0db3ff2bb5b2?action=share&creator=14064846)?

**Comment by daniloreis88** [comment]
Isso mesmo  1.3.3 POST
Send List
https:///message/sendList/:instanceName

Em qua., 9 de out. de 2024, 14:57, Cleber Wilson ***@***.***>
escreveu:

**Comment by daniloreis88** [comment]
{
	"status": 404,
	"message": "Cannot POST /message/sendList/teste",
	"error": "Not Found"
}

**Comment by jrCleber** [comment]
Vou verificar.

**Comment by daniloreis88** [comment]
{
	"status": 404,
	"message": "Cannot POST /message/sendButtons/teste",
	"error": "Not Found"
}  botao tambem esta sem

**Comment by coutoemanuel** [comment]
Os envios de botões estão funcionando?

**Comment by rdev-comp** [comment]
> Os envios de botões estão funcionando?

Aqui não estão. O método "sendButtons" parece ter parado de funcionar. Se você enviar apenas a imagem, titulo, descrição e rodapé, sem nada no node "buttons", a mensagem chega. Mas se enviar completo, a mensagem nem mostra.

**Comment by jrCleber** [comment]
Botões e listas são sempre instáveis. Não é possível garantir 100% do seu funcionamento.
Caso essa funcionalidade for um requisito importante para o seu negócio, recomendo o uso da api oficial.

Beleza👍🏼!
