### ISSUE TITLE
Send Buttons choices 

### ISSUE THREAD

**Issue by f-amine** [code-chat-br/whatsapp-api#155]
### I have searched for similar requests on GitHub and found none.

- [X] Yes

### Feature type:

Endpoint

### What problem does the feature aim to solve?

Is it possible to add a sendButton endpoint similar to the waha service ? 
it would be really useful for integrating specific workflows 

### Provide specific examples of how this feature could be used.
This can include scenarios or use cases where the feature would be particularly beneficial.

_No response_

**Comment by jrCleber** [comment]
[See Here](https://www.postman.com/codechat/workspace/codechat-api/request/14064846-e6177d15-6b10-4290-81d6-da96d74edfe4?action=share&source=copy-link&creator=14064846&ctx=documentation)

**Comment by f-amine** [comment]
it is not accessible from the latest version ( the docker version ) ?
