### ISSUE TITLE
Bug with ButtonMessage send when u include a thumbnail 

### ISSUE THREAD

**Issue by f-amine** [code-chat-br/whatsapp-api#156]
### I have searched for similar issues on [GitHub](https://github.com/code-chat-br/whatsapp-api/issues) and found none.

- [X] Yes

### Steps to reproduce the issue

call the send Button with a thumbnail 

### Describe what you expected to happen.

A message with the image and button choices this used to work on previous versions but when I use the latest version this issue happens

### Explain what actually happens when you follow the steps above.

The message displayed in whatsapp shows : your version of whatsapp doesnt support it . update whatsapp ( my whatsapp is the latest bersion )

### Enter the version number found in the `version` property of **package.json**.

1.3.3

### If possible, add screenshots or videos that illustrate the issue.
This can be extremely helpful to better understand the issue.

_No response_

### The environment in which the application is running

Linux

### Please attach any logs that might be related to the issue.
If the logs contain sensitive information, consider sending them privately to one of the project maintainers.

_No response_

**Comment by jrCleber** [comment]
Messages with buttons are always unstable.

It is not possible to guarantee 100% that they will work.

If it works without the thumbnail, remove the thumbnail. Send a message with an image first and then the buttons.

**Comment by f-amine** [comment]
alright just letting you know since I think yesterdays updates are what caused it tested without both versions just now
