### ISSUE TITLE
sendButtons aparentemente modificado pela Meta

### ISSUE THREAD

**Issue by rdev-comp** [code-chat-br/whatsapp-api#159]
### Pesquisei problemas semelhantes no [GitHub](https://github.com/code-chat-br/whatsapp-api/issues) e não encontrei nenhum.

- [X] Sim

### Quais passos para chegar ao problema?

Tentei enviar uma mensagem pelo método "sendButtons" e a mensagem não é exibida. 

### Descreva o que você esperava que acontecesse.

Mensagem deveria chegar corretamente, no formato de botões, com uma image, titulo, descrição e rodapé.

### Explique o que realmente acontece quando você segue os passos acima.

A mensagem não é exibida em dispositivos "ios" e "android". Na versão desktop mostra a mensagem "Não é possível exibir essa mensagem neste dispositivo. Abra o WhatsApp no seu celular para ver a mensagem". Porém, ao abrir o celular, a mensagem sequer é exibida.

### Insira o número da sua versão que está na propriedade `version` do **package.json**.

1.3.3

### Se possível, adicione capturas de tela ou vídeos que ilustrem o problema.
Isso pode ser extremamente útil para entender melhor o problema.

![image](https://github.com/user-attachments/assets/74c87c32-c467-4f60-bd63-dcca68a433f9)
![image](https://github.com/user-attachments/assets/8e2d953c-ffc4-4318-87ef-64658caf12a1)

### O ambiente no qual a aplicação está em execução

Linux

### Por favor, anexe os logs que possam estar relacionados ao problema.
Se os logs contiverem informações sensíveis, considere enviá-los de forma privada para um dos mantenedores do projeto.

```http
POST /message/sendButtons/marketing HTTP/1.1
Content-Type: application/json
Accept: application/json
apikey: xxx
User-Agent: PostmanRuntime/7.42.0
Cache-Control: no-cache
Postman-Token: d2cbda63-f2da-411b-9a0c-505cbd24e4ab
Host: 191.252.193.9:8084
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
 
{
  "number":"8596416511",
  "buttonsMessage": {
    "title":"TITLE EXAMPLE",
    "description":"TESTE TEXTO ESTATICO",
    "footer":"FOOTER EXAMPLE",
    "buttons":[
      {
        "type":"copy",
        "displayText":"DISPLAY TEXT EXAMPLE",
        "copyCode":"COPY CODE EXAMPLE"
      }
    ]
  }
}
 
```

```http
HTTP/1.1 201 Created
X-Powered-By: Express
Content-Type: application/json; charset=utf-8
Content-Length: 713
ETag: W/"2c9-ZOqXTa04DIjRS04Zu31S6Rw/7OE"
Date: Sat, 23 Nov 2024 14:31:25 GMT
Connection: keep-alive
Keep-Alive: timeout=5
 
{
  "id": 199730,
  "keyId": "01JDCPYHS7DBQWTDZKF5K9FYB3",
  "keyFromMe": true,
  "keyRemoteJid": "8596416511@s.whatsapp.net",
  "keyParticipant": "",
  "pushName": "",
  "messageType": "viewOnceMessage",
  "content": {
    "message": {
      "messageContextInfo": {
        "deviceListMetadata": {},
        "deviceListMetadataVersion": 2
      },
      "interactiveMessage": {
        "body": {
          "text": "TITLE EXAMPLE\n\nTESTE TEXTO ESTATICO\n"
        },
        "footer": {
          "text": "FOOTER EXAMPLE"
        },
        "nativeFlowMessage": {
          "buttons": [
            {
              "name": "cta_copy",
              "buttonParamsJson": "{\"display_text\":\"DISPLAY TEXT EXAMPLE\",\"copy_code\":\"COPY CODE EXAMPLE\"}"
            }
          ],
          "messageParamsJson": "{\"from\":\"api\",\"templateId\":\"01JDCPYHGCQMYPSXACJK9W8CQ6\"}"
        }
      }
    }
  },
  "messageTimestamp": 1732372285,
  "instanceId": 3,
  "device": "web",
  "isGroup": false
}
```

**Comment by jrCleber** [comment]
Botões e listas são sempre instáveis. Não é possível garantir 100% do seu funcionamento.
Caso essa funcionalidade for um requisito importante para o seu negócio, recomendo o uso da api oficial.

Beleza👍🏼!
