### ISSUE TITLE
Problem scanning QR Code

### ISSUE THREAD

**Issue by WesleyMarinho** [code-chat-br/whatsapp-api#19]
When scanning the QrCode in the terminal in all 6 attempts it does not connect. Tested on normal whatsapp and whatsapp business.

What can I do to fix this?

**Comment by sanderdeking** [comment]
Solved, just give a full restart on the server :)

**Comment by hosamalzagh** [comment]
we work fine try small window

**Comment by jrCleber** [comment]
> Ao escanear o QrCode no terminal nas 6 tentativas ele não se conecta. Testado no whatsapp normal e no whatsapp business.
> 
> O que posso fazer para esclarecer isso?
@WesleyMarinho 
In which environment are you testing the application?

**Comment by hosamalzagh** [comment]
it not work form first time my be in 5 or  7 try or 10

**Comment by fluxxo10** [comment]
did you solve it friend?
