### ISSUE TITLE
groups in messages.set + Missing initials webhooks

### ISSUE THREAD

**Issue by jeankassio** [code-chat-br/whatsapp-api#2]
Olá, gostaria de iniciar elogiando seu trabalho, amei seu projeto e estou desenvolvendo em cima dele um sistema.
Quando faço a conexão, recebo os seguintes webhooks:
chats.set, contacts.upsert e messages.set.
No messages.set há também mensagens de grupos, onde não é possível identificar quem é que enviou a mensagem, apenas de qual grupo a mensagem veio, e creio eu que esteja faltando webhooks iniciais.

----------------------------

Hello, I would like to start praising your work, I loved your project and I am developing a system based on it.
When I connect, I get the following webhooks:
chats.set, contacts.upsert and messages.set.
In messages.set there are also group messages, where it is not possible to identify who sent the message, only which group the message came from, and I believe that initial webhooks are missing.

![](https://i.imgur.com/rDcWLlU.png)

**Comment by jrCleber** [comment]
Merge [pull request](https://github.com/code-chat-br/whatsapp-api/commit/b974041b498701ef6765bf788c624be00391da80) https://github.com/code-chat-br/whatsapp-api/pull/3 from jeankassio/main
