### ISSUE TITLE
[BUG] buttons and lists stopped working 

### ISSUE THREAD

**Issue by hosamalzagh** [code-chat-br/whatsapp-api#21]

**Comment by jrCleber** [comment]
It's a compatibility issue with the app itself.
Do not use whatsapp business to send these types.

**Comment by hosamalzagh** [comment]
i use normall whatsup not business
i think https://github.com/WhiskeySockets/Baileys/issues/56 have same bug
@jrCleber

**Comment by cobraprojects** [comment]
I have the same issue,
It was working fine untill I test it today

**Comment by jrCleber** [comment]
Buttons and lists always have compatibility issues.
And do not use whatsapp business to work with this type of message. And preferably use texts.
