### ISSUE TITLE
Bad Request when sending message - "SessionError: No sessions"

### ISSUE THREAD

**Issue by caiquezanetoni** [code-chat-br/whatsapp-api#22]
some instances suddenly stop sending messages 

response:
`{
	"status": 400,
	"error": "Bad Request",
	"message": [
		"SessionError: No sessions"
	]
}`

/connectionState response: 
`{
	"state": "open",
	"statusReason": 200
}`

**Comment by jrCleber** [comment]
Reread the qr code.

**Comment by caiquezanetoni** [comment]
ok, I updated to the latest version and the instance started sending the messages again. Is this a common problem?

**Comment by caiquezanetoni** [comment]
I had the same problem with another instance.

**Comment by caiquezanetoni** [comment]
when updating the service by portainer, and doing a re-pull of the image, the instances work again

**Comment by fhonline** [comment]
randomly, the error message NO SESSIONS has been displayed, for a random contact... the procedure returns to normal if you reconnect whatsapp or restart the api

![image](https://github.com/code-chat-br/whatsapp-api/assets/95591514/1cd2eab7-bbe9-4f43-89de-4a586d353dd5)

**Comment by fhonline** [comment]
> Reread the qr code.

yes that solves it, but daily, in the midst of several connections, this is becoming a habit to appear, is there no way to kill this bug?

**Comment by fhonline** [comment]
This problem is solved using Redis to control the session... just enable it in the env.yml file

**Comment by 1579091** [comment]
its possible to fix without redis?
Some times i need to restart codechat because i get this error:
`[CodeChat]  199709   -  Wed May 31 2023 19:46:53     ERROR   [WAStartupService]  [object]
SessionError: No sessions
    at Object.5511958349862:17.0 [as awaitable] (/home/ubuntu/whatsapp-api/node_modules/libsignal/src/session_cipher.js:71:23)
    at async _asyncQueueExecutor (/home/ubuntu/whatsapp-api/node_modules/libsignal/src/queue_job.js:20:29)`
    
  I dont need to read qrcode again, but i need to restart and connection returns.
  
  Or someone can learn me how to up codechat with redis like the last answer

**Comment by eltonhbm** [comment]
I am also having the same problem.
Among several messages, the error occurs on a single number.
It is also resolved by restarting the container, without the need to read the QR Code again.

**Comment by ichimarurei** [comment]
> I am also having the same problem. Among several messages, the error occurs on a single number. It is also resolved by restarting the container, without the need to read the QR Code again.

same with me
