### ISSUE TITLE
whatsapp online 24 horas

### ISSUE THREAD

**Issue by rafaWPP** [code-chat-br/whatsapp-api#31]
como não deixa q o whatsapp fique online 24 horas por dia

**Comment by jrCleber** [comment]
Por padrão, o whatsapp fica com o status online durante toda a conexão. Mas, vc pode configurar essa opção na função que faz a conexão atribuindo a propriedade [markOnlineOnConnect](https://github.com/WhiskeySockets/Baileys#configuring-the-connection).

**Comment by rafaWPP** [comment]
eu nao fiz nenhuma modificação na lib
onde eu atribuo  essa propriedade no code chat ?
