### ISSUE TITLE
sessões

### ISSUE THREAD

**Issue by rafaeld03** [code-chat-br/whatsapp-api#32]
bom dia

já aconteceu algumas vezes da sessão estar ativa no celular, mas a apikey gerada no momento da conexão não funcionar mais
existe como atualizar a apikey ou descobrir o porque disso?

**Comment by jrCleber** [comment]
Bom dia! Isso não é possível.
Tem certeza está usando a credencial correta?

Para recuperar a credencial, no mometo, é necessário criar uma outra aplicação que manipule essas credenciais.

**Comment by rafaeld03** [comment]
sim, 3 instancias com as credenciais corretas
hoje amanheceu as 3 com "Unauthorized"

**Comment by jrCleber** [comment]
Qual o tipo de credencial vc está utilizando?

**Comment by jrCleber** [comment]
Não! Isso é improvável.
Mande a sua dúvida no grupo junto com o seu arquivo de configuração env.yml.

**Comment by rafaeld03** [comment]
pode passar link do grupo?

**Comment by jrCleber** [comment]
[README](https://github.com/code-chat-br/whatsapp-api/blob/main/README.md)
