### ISSUE TITLE
Numeros de portugal nao envia mensagem 

### ISSUE THREAD

**Issue by rafaWPP** [code-chat-br/whatsapp-api#33]
Números de portugal dis q nao esta no whatsapp,  testei 2 numeros , e não envia mensagem

**Comment by jrCleber** [comment]
A aplicação apresentou algum erro?

**Comment by rafaWPP** [comment]
Não, 
Testei portugal e Irlanda
Os dois dizem que o número não está no whatsapp 

Mas não dá erro na api
