### ISSUE TITLE
audios mp3 enviados pelo anexo esta ficando mudo para a pessoa que recebe no celular

### ISSUE THREAD

**Issue by alexlutke** [code-chat-br/whatsapp-api#36]
audios mp3 enviados pelo anexo esta ficando mudo para a pessoa que recebe no celular...

Quando anexamos um audio mp3 na conversa e enviamos ao contato... pelo celular o audio fica mudo, a pessoa nao consegue ouvir... o atendente consegue ouvir normal. nos testes também notei que se o cliente estiver usando a versão web whatsapp, ai ele consegue ouvir o audio anexado. O problema esta ocorrendo quando é ouvido por celular.

O erro acontece desde da verão [v2.16.0] do chatwoot .. na versão 2.17.1 a situação piorou... agora nem o audio gravado no proprio chat a pessoa consegue ouvir no celular...

**Comment by jrCleber** [comment]
O tipo de áudio que é criado no chatwoot é incompatível com o tipo de áudio suportado pelo whatsapp.
É preciso converter o áudio antes de enviá-lo à aplicação.
