### ISSUE TITLE
converter gravação de audio mp3 para ogg

### ISSUE THREAD

**Issue by DRIMOL** [code-chat-br/whatsapp-api#41]
em teoria a api funciona para enviar gravação de audio em mp3, mas, notei que não toca em iphone quando enviado em mp3, seria interessante ter uma forma já nativa de converter audios mp3 para ogg.

**Comment by jrCleber** [comment]
A conversão de áudio em JavaScript pode exigir recursos significativos do dispositivo do usuário e pode levar algum tempo para ser concluída, dependendo do tamanho do áudio e da capacidade do dispositivo.
Sugiro tratar o áudio antes de enviá-lo à API.
