### ISSUE TITLE
 Docker Jwt Expiry Cannot  increase

### ISSUE THREAD

**Issue by jigjosh** [code-chat-br/whatsapp-api#43]
we are not able to increase the JWT Expiry and it stick with 3600S === 1h.
it seem the issue with env.config.ts which using  Number.isInteger function 
for checking AUTHENTICATION_JWT_EXPIRIN_IN environment

**Comment by jrCleber** [comment]
Make the change when creating the container.
* **AUTHENTICATION_JWT_EXPIRIN_IN:** is a container environment variable that can be set/changed at the time of its creation.

**Comment by jigjosh** [comment]
yes but it seem when try to creating the container with -e AUTHENTICATION_JWT_EXPIRIN_IN=604800  in the env.config.ts it check Number.isinteger(‘604800’) which return false and it set 3600

**Comment by jrCleber** [comment]
I'll check it out.
