### ISSUE TITLE
notificação não toca

### ISSUE THREAD

**Issue by santistatec** [code-chat-br/whatsapp-api#46]
Olá amigo blz, ao conectar na api whatsapp fica sem receber o som da notificação, ao desconectar volta a funcionar perfeitamente
 Teria algo que eu poderia estar fazendo para voltar tocar as notificações de mensagens recebidas ?

Obrigado.

**Comment by jrCleber** [comment]
Sim! É que o status fica sempre como online.
Imagine que vc se conecta ao o WhatsApp Web, e nunca fechasse a aba do navegador ou deixasse de ter iteração com o WhatsApp. É assim que a API funciona.

Há uma forma de alterar isso, mas é preciso reconetar o WhatsApp alterando uma propriedade no socket de conexão.
