### ISSUE TITLE
Error starting latest version

### ISSUE THREAD

**Issue by GarethWright** [code-chat-br/whatsapp-api#48]
> whatsapp-api@1.2.1 start:prod
> bash start.sh

> removing dist

> transpiling...

> whatsapp-api@1.2.1 build
> tsc

src/whatsapp/controllers/instance.controller.ts:24:22 - error TS2554: Expected 4 arguments, but got 3.

 24     const instance = new WAStartupService(
                         ~~~~~~~~~~~~~~~~~~~~~
 25       this.configService,
    ~~~~~~~~~~~~~~~~~~~~~~~~~
... 
 27       this.repository,
    ~~~~~~~~~~~~~~~~~~~~~~
 28     );
    ~~~~~

  src/whatsapp/services/whatsapp.service.ts:106:5
    106     private readonly cache: RedisCache,
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    An argument for 'cache' was not provided.

Found 1 error in src/whatsapp/controllers/instance.controller.ts:24

> Successfully build 

> Starting application...

node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module '/root/whatsapp-api/dist/src/main.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',

**Comment by jrCleber** [comment]
#45
