### ISSUE TITLE
Audio playing only Whatsapp Web

### ISSUE THREAD

**Issue by saintclair** [code-chat-br/whatsapp-api#49]
Audios working only on Whatsapp web (type: mp4 or ogg).

**OGG FILE**
https://download2262.mediafire.com/sdzbk5cia23gU4Mj1wcFQ2L89YiRglf1a44CftfvasXWnwaeesE9mGG_TMzsdP1_Di_ifBHseLQqqnjQ4PayBlVP8New7c-0l4K_sMDo2-Hfl9VOjYMpecnauZId35sPcdAdk1dVwvNQaFJsVmCdWrL9DZS2marnWNoUOazbXaXJ8G0S/x162d7vy2j0o3xq/Dep-Jennifer-P2x.ogg

**MP4 FILE**
https://github.com/code-chat-br/whatsapp-api/assets/911709/c26a5502-c8e0-4de0-bf0a-053dea8e6a13

Documentation Whatsapp: https://developers.facebook.com/docs/whatsapp/on-premises/reference/media

**Comment by jrCleber** [comment]
#60 Check if this commite solved your problem.
