### ISSUE TITLE
Não é possível definir uma porta especifica para o container Docker

### ISSUE THREAD

**Issue by Sulivan1999** [code-chat-br/whatsapp-api#50]
Olá!
Como posso definir uma porta especifica para um container Docker, utilizando a imagem oficial do CodeChat? Não encontrei essa especificação para as variáveis de ambiente.

Por padrão, a exposição é realizada para a porta 8083, más e se estiver rodando mais um container com a mesma imagem?

**Comment by jrCleber** [comment]
Vc precisa definir uma porta no seu servidor que aponta para a porta exposta no container.

https://docs.docker.com/engine/reference/commandline/port/
