### ISSUE TITLE
Quebra de linha entre nome do operador e msg

### ISSUE THREAD

**Issue by clarcksp** [code-chat-br/whatsapp-api#57]
Olá, gostaria de saber se existe a possibilidade dele ter uma quebra de linha entre o nome do operador e a mensagem que será enviada? 
Ex:
**<Nomedousuario>**
<Mensagem que será enviada>

**Comment by jrCleber** [comment]
Não compreendi a sua dúvida.

**Comment by clarcksp** [comment]
> Não compreendi a sua dúvida.

Olá, bom dia.
Vou contextualizar melhor.
Eu utilizo o chatwoot integrado ao codechat utilizando o integrador **chatwoot-codechat**
Bem o que eu percebi foi o seguinte, quando é transmitido uma mensagem pelo chatwoot ao destinatário chega da seguinte forma:
<nome do usuário> : <Mensagem>

Sempre na mesma linha.
Eu gostaria de saber se existe a possibilidade de alterar o formato para que o usuário fique na linha superior e a mensagem comece na segunda linha, desta forma:

<nome do usuário> :
<Mensagem>

Sempre começando na linha abaixo o texto da mensagem.

**Comment by jrCleber** [comment]
Entendi! Está aplicação não possui integração nativa com o chatwoot. As integrações que existem, não foram desenvolvidas por essa organização.

Abra uma issue diretamente no projeto da integração que vc está utilizando.
👊🏻👍🏼
