### ISSUE TITLE
k8 liveness endpoint

### ISSUE THREAD

**Issue by felipefontoura** [code-chat-br/whatsapp-api#58]
Hello folks,

first of all, congrats for this amazing project, it's really works for us sending transactions and marketing messages thought n8n workflows.

The last month we're deployed codechat in kubernetes infra, and it's working very well. But, for working 100% we need to define the liveness endpoint for k8.

Question: have any global endpoint to returns if all instances are connected and working well?

Thanks!

Refs: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-liveness-http-request

**Comment by jrCleber** [comment]
Good morning!
Exit the route [fetchInstances](https://github.com/code-chat-br/whatsapp-api/blob/c03538c4114545ffdb168b41d1eccbf50a134638/postman.json#L122). In it, you pass your *[globalApiKey](https://github.com/code-chat-br/whatsapp-api/blob/c03538c4114545ffdb168b41d1eccbf50a134638/src/dev-env.yml#L146)* to retrieve all instances.
