### ISSUE TITLE
not getting the whole messages.set on connection open 

### ISSUE THREAD

**Issue by saadnust** [code-chat-br/whatsapp-api#61]
Webhook receives only a limited set of messages on connection open, not all.

Which makes to leave unread msgs go unprocessed forever

**Comment by jrCleber** [comment]
This is common behavior. it is possible that you find this information in the **'chats.set'** or **'chats.upsert'** event.

**Comment by saadnust** [comment]
chat.set gives the Jid and chat Id, but I want to get messages by that Jid
or ChatId.

**Comment by jrCleber** [comment]
All messages, whether received or sent, are notified through the **"messages.upsert"** event.
