### ISSUE TITLE
File upload endpoint not working with base64

### ISSUE THREAD

**Issue by FelipeDeveloperFullStack** [code-chat-br/whatsapp-api#63]
Hey guys

I'm trying to use the endpoint POST {{baseUrl}}/message/sendMedia/{{instance}}, but when passing the base64 of a .pdf file, it's not working. It's returning me the message: "Owned media must be a url".

What am I doing wrong? can anybody help me?

![image](https://github.com/code-chat-br/whatsapp-api/assets/9463295/3ee4efc6-789e-4a61-b79a-ec0eb7dc5d4d)
![image](https://github.com/code-chat-br/whatsapp-api/assets/9463295/79d3bf98-301c-4389-a875-408795d57560)

**Comment by jrCleber** [comment]
What is your api version?
If it is lower than [v1.2.6](https://github.com/code-chat-br/whatsapp-api/releases/tag/v1.2.6), please update.

Access the route: http://localhost:8083/docs and correct your application.

**Comment by FelipeDeveloperFullStack** [comment]
@jrCleber 

Thank you, it helped me a lot.

The version is the same, I had not updated it was the postman.json version, I updated it here and used the "/message/sendMediaFile" endpoint.

But, I don't know that I had the swagger by the "http://localhost:8083/docs" endpoint, they could later add it in the README.md it will help other devs, if not I can open a pull request to request this update. It will be very useful.

Thank you for your help.

**Comment by FelipeDeveloperFullStack** [comment]
@jrCleber 

Thank you, it helped me a lot.

The version is the same, I had not updated it was the postman.json version, I updated it here and used the "/message/sendMediaFile" endpoint.

But, I don't know that I had the swagger by the "http://localhost:8083/docs" endpoint, they could later add it in the README.md it will help other devs, if not I can open a pull request to request this update. It will be very useful.

Thank you for your help.
