### ISSUE TITLE
Socketio Redis Crash API

### ISSUE THREAD

**Issue by geandersonlenz** [code-chat-br/whatsapp-api#64]
when we set the env file redis true and set the url, after a while of use the api returns the error max reached person, checking the logs is the loss of the socket connection due to an error in redis. There are several threads dealing with the subject.
https://stackoverflow.com/questions/71529057/how-can-i-restore-sockets-in-rooms-after-redis-crashes-with-socket-io-redis-adap

**Comment by jrCleber** [comment]
What version of your api?
