### ISSUE TITLE
"SessionError: No sessions"

### ISSUE THREAD

**Issue by JorgeDorio** [code-chat-br/whatsapp-api#7]
Eu estou recebendo o seguinte erro:

```json
{
    "status": 400,
    "error": "Bad Request",
    "message": [
        "SessionError: No sessions"
    ]
}
```

Para toda mensagem de desejo enviar.

- Tenho uma instância criada
- A instancia foi conectada
- A conexão está aberta

Não sei se não encontrei, mas seria legal ter uma documentação

**Comment by jrCleber** [comment]
Esse erro está associado a qual evento?
Está se repetindo com qual frequência?

**Comment by JorgeDorio** [comment]
Todas as rotas de Send Message, mas pra simplificar, estou tentando a de enviar texto simples

A autorização é via apikey, o payload é o mesmo disponibilizado na collection do postman, apenas com a alteração para o número que desejo enviar.

Tentei rodar em dev e em prod, mas ambos retornaram o mesmo erro.

Inclusive, a proncipio não tinha conseguido transpilar pois estava dando erro de tipagem na função `connectToWhatsapp` de `whatsapp.service`:

```
The inferred type of 'connectToWhatsapp' cannot be named without a reference to '@adiwajshing/baileys/node_modules/@hapi/boom'. This is likely not portable. A type annotation is necessary.

382   public async connectToWhatsapp() {
                   ~~~~~~~


Found 1 error in src/whatsapp/services/whatsapp.service.ts:382
```

Removi a validação de tipo do tsconfig e consegui rodar em prod.

**Comment by jrCleber** [comment]
Intalou com o npm ou com o yarn?
Passando o mouse sobre a linha 382, qual é a mensagem?

Esse erro é bem incomum...

Acessa o 👉🏼 **[grupo ](https://chat.whatsapp.com/HyO8X8K0bAo0bfaeW8bhY5)** e posta a sua dúvida lá.

**Comment by glauco-oliveira** [comment]
Estou tendo exatamente o mesmo problema, todas as rotas de envio de mensagens retorna sempre Session error

**Comment by jrCleber** [comment]
> * Dê o comando: **git pull**;
> * Delete a pasta **node-modules**;
> * Reinstale as dependências: **npm i**;
> * Inicie novamente a aplicação.

@glauco-oliveira executa as instruções acima.

**Comment by jrCleber** [comment]
> Intalou com o npm ou com o yarn? Passando o mouse sobre a linha 382, qual é a mensagem?
> 
> Esse erro é bem incomum...
> 
> Acessa o 👉🏼 **[grupo ](https://chat.whatsapp.com/HyO8X8K0bAo0bfaeW8bhY5)** e posta a sua dúvida lá.

@glauco-oliveira
