### ISSUE TITLE
Versão 1.2.7 quebrada

### ISSUE THREAD

**Issue by hnmendes** [code-chat-br/whatsapp-api#70]
Notei que a nova versão da api que você publicou está quebrada, provavelmente deve ser algo bem simples de configuração.

Envolve os arquivos:

whatsapp.module.ts
env.config.ts

Tentei dar uma olhada, mas não entendi bem o erro.

**Comment by jrCleber** [comment]
Poste o erro aqui.

**Comment by hnmendes** [comment]
Era esse o erro:

![image](https://github.com/code-chat-br/whatsapp-api/assets/16869941/32a0878c-3061-4211-98b9-8bfc2c5b0f93)

Mas foi sanado com esse commit:

https://github.com/code-chat-br/whatsapp-api/commit/7f41b85f378ad04eb3adb0abd2cba23d7e485ee4
