### ISSUE TITLE
Authorization com o mesmo nome da instância

### ISSUE THREAD

**Issue by WesleyjanLacerda** [code-chat-br/whatsapp-api#72]
Gostaria de mudar a forma de leitura do token, em vez ser o hash jwt ou apiKey, o token fosse o mesmo nome da conexão/instância, como poderia aplicar isso ?

**Comment by jrCleber** [comment]
Vc precisa modificar uma série de arquivos:

1. [Instance Controller](https://github.com/code-chat-br/whatsapp-api/blob/main/src/whatsapp/controllers/instance.controller.ts)
2. [Auth Service](https://github.com/code-chat-br/whatsapp-api/blob/main/src/whatsapp/services/auth.service.ts)
3. [Auth Guard](https://github.com/code-chat-br/whatsapp-api/blob/main/src/whatsapp/guards/auth.guard.ts)

Isso é só o primeiro passo para reprogramar o método de autenticação.
