### ISSUE TITLE
Problemas para enviar áudio

### ISSUE THREAD

**Issue by mateuslcsilva** [code-chat-br/whatsapp-api#73]
Estou com problemas para enviar áudio pelo codechat. A mensagem de áudio aparece apenas para whatsapp web no navegador, mas não aparece nem pra whatsapp web instalado e nem para celular.

Atualizei o codechat semana passada, e antes disso funcionava. Não achei nenhuma alteração que precisasse ser feita para funcionar esse envio.

Alguém enfrentou o mesmo problema?

ENG
Im having problems to send audio using codechat. The media appears only on whatsapp web on browser, but doesnt appear on cellphone or whatsapp PC app.

Got my codechat updated last week, and stop working after that. I coudnt fount any change on the way of use the endpoint.

Someone getting the same problem?

**Comment by mateuslcsilva** [comment]
Estava usando o endpoint sendMedia, alterei para sendWhatsAppAudio e funcionou perfeitamente.

I was using sendMedia, changed to sendWhatsAppAudio and it worked well.

**Comment by mrlazarias** [comment]
Mesma coisa, mesmo com o endpoint sendWhatsAppAudio
