### ISSUE TITLE
Problema ao enviar mensagem. Bad Request.

### ISSUE THREAD

**Issue by mateuslcsilva** [code-chat-br/whatsapp-api#74]
Estou com um problema para enviar mensagem, usando os endpoints sendText, sendMedia e sendWhatsAppAudio. O problema acontece de uma hora pra outra, alguns números funcionam outros não, outros passam a não funcionar. Vi em uma issue que poderia funcionar configurar uma fila no redis pra lidar com as requests, mas continuo tendo o mesmo problema. Alguém já lidou com essa situação?

ENG
Im having a problem sending a message using the sendText, sendMedia and sendWhatsAppAudio endpoints. The problem happens out of nowhere, some numbers work, others don't, others stop working. I saw in an issue that it could work to configure a queue in redis to handle requests, but I still have the same problem. Has anyone dealt with this same issue?

**Comment by cassianomansano** [comment]
Tb estou com a mesma situação, alguma novidade?

**Comment by jrCleber** [comment]
Tentem reconectar o whatsapp para sincronizar novamente as chaves.

**Comment by mateuslcsilva** [comment]
Isso resolve, mas é recorrente, volta a acontecer em pouco tempo.

**Comment by cassianomansano** [comment]
> Tentem reconectar o whatsapp para sincronizar novamente as chaves.

Aqui atualizei e não tive mais problema

**Comment by jrCleber** [comment]
> Isso resolve, mas é recorrente, volta a acontecer em pouco tempo.

O seu problema foi resolvido @mateuslcsilva?

**Comment by mateuslcsilva** [comment]
Não consegui resolver de maneira nenhuma. Configurei fila no redis como foi citado em uma issue anterior, atualizei e continua com o problema, quando reinicio o serviço ele volta ao normal, mas em pouco tempo volta o problema.

**Comment by jrCleber** [comment]
@mateuslcsilva Poste aqui qual o erro recebido.

**Comment by PuseTV-Repository** [comment]
Hi, can anyone help me? QR code is not generated

**Comment by mateuslcsilva** [comment]
@jrCleber Não recebi mais nenhuma reclamação de usuário disso acontecendo pra poder trazer a resposta, e era algo que recebia pelo menos 3 reclamações por dia.

Acredito que tenha sido resolvido.

Obrigado pela atenção!

**Comment by CezarASilveira** [comment]
Eu estou tentando implementar o codechat e estou tentando dificuldades.
Poruqe tenho que gerar o QRcode e pra que ele serve ?
Poruqe quando busco a status da conexão fica sem assim?
{
    "state": "connecting",
    "statusReason": 200
}
E porque que quando tento enviar uma mensagem eu recebo esse retorno?
{
    "status": 400,
    "error": "Bad Request",
    "message": [
        {
            "jid": "553288551364@s.whatsapp.net",
            "exists": false
        }
    ]
}

Alguém consegue me ajudar por favor ?

**Comment by jrCleber** [comment]
> ![Captura de tela 2023-10-09 093750](https://user-images.githubusercontent.com/95585079/273591135-acf7fa85-9149-44e3-9812-335776c6fde9.png)

Na nova versão, há um endpoint que realiza o reload da conexão para tratar esses casos.

**Comment by MattCarneiro** [comment]
> > ![Captura de tela 2023-10-09 093750](https://user-images.githubusercontent.com/95585079/273591135-acf7fa85-9149-44e3-9812-335776c6fde9.png)
> 
> Na nova versão, há um endpoint que realiza o reload da conexão para tratar esses casos.

Qual o endpoint e qual a versão? 1.2.8?
