### ISSUE TITLE
Health Check

### ISSUE THREAD

**Issue by azisaka** [code-chat-br/whatsapp-api#75]
Acho que valeria a pena ter um endpoint para indicar que a aplicação está funcionando como esperado: conexões com os bancos de dados OK, fazer um teste de envio de mensagem pra validar que a comunicação com o Whatsapp está OK. 

O que vc acha @jrCleber? Posso fazer aqui, mas achei melhor pedir sua opinião antes de aparecer com código aqui que vc nem queria hehe

**Comment by jrCleber** [comment]
Isso não é uma questão da api. É algo relacionado à infraestrutura.
O ideal e criar uma aplicação que gerencie as instancias.
