### ISSUE TITLE
Verificar se Número é Whats

### ISSUE THREAD

**Issue by cassianomansano** [code-chat-br/whatsapp-api#77]
Olá pessoal,

Sabem dizer se é possível verificar se um número é whats antes de proceder com o envio? 
Na documentação não achei nada a respeito, acredito q não tenha método/endpoint para tal retorno.
Caso não tenha quem sabe pode ser um recurso interessante, ai gostaria de deixar minha sugestão.

Vlw.

**Comment by jrCleber** [comment]
Existe o endpoint [/chat/whatsappNumbers/:instanceName](https://www.postman.com/codechat/workspace/codechat-whatsapp-api/api/fbe06c7b-7647-4c71-81ee-841f5b2e90d8/request/14064846-178455cf-4fe9-4013-b87f-fc9d2c16265b?collection=14064846-015c60ca-09fd-4b9a-9174-f92df30904dd&version=c8323016-3d08-4806-890c-704dc89a10e4) para esse fim.
