### ISSUE TITLE
PROBLEM GENERATING QR CODE USING POSTMAN

### ISSUE THREAD

**Issue by PuseTV-Repository** [code-chat-br/whatsapp-api#80]
To begin with, thank you for your collaboration. I am testing your API and I create the instance correctly, and I manage to enter where the QR code should be generated, I give the button to generate and nothing is generated. I await your answer

**Comment by jrCleber** [comment]
Show error logs.

**Comment by PuseTV-Repository** [comment]
When I press the button "Generate qrcode" 
it shows me this in console

![error](https://github.com/code-chat-br/whatsapp-api/assets/123263066/d4734234-b9f7-4952-b46a-7fcef8030fb8)

**Comment by PuseTV-Repository** [comment]
![image](https://github.com/code-chat-br/whatsapp-api/assets/123263066/b9ab15e8-6cd8-46cb-8746-09a51d1d1ba6)

**Comment by vonneumann23** [comment]
I have the same problem

**Comment by jrCleber** [comment]
Sorted out. See commit b2f1430.
