### ISSUE TITLE
Problem to use endpoint getBase64FromMediaMessage

### ISSUE THREAD

**Issue by mateuspontesmoares** [code-chat-br/whatsapp-api#85]
I'm trying to use a endpoint {{baseUrl}}/chat/getBase64FromMediaMessage/:instanceName, but a received error in my request.

The response

`POST
{{baseUrl}}/chat/getBase64FromMediaMessage/:instanceName

BODY
{
  "key": {
    "id": "3AE075054A8A5B0E00A4"
  }
}

RESPONSE
{
    "status": 400,
    "error": "Bad Request",
    "message": [
        "TypeError: Cannot read properties of undefined (reading 'message')"
    ]
}`

**Comment by dulkith** [comment]
[Deprecated] This endpoint retrieves the Base64 representation of the content of a media message for the specified instance.
