### ISSUE TITLE
Forward message?

### ISSUE THREAD

**Issue by ninoppp** [code-chat-br/whatsapp-api#90]
hey
is it possible to forward a message via this api?

Or, alertnatively, to send media via url instead of including the binary data?

**Comment by jrCleber** [comment]
Hello! Good morning.
Message forwarding is not yet available. But sending URLs does.
Check this endpoint [sendMedia](https://github.com/code-chat-br/whatsapp-api/blob/81802915e12cc0b1a0ec3c94d20dde9ccd8694d9/src/docs/swagger.yaml#L327), or here [Send Media](https:/ /www.postman.com/codechat/workspace/codechat-whatsapp-api/request/14064846-28467e5d-e39f-415d-93fc-be0ca47cf13f?ctx=documentation).
