### ISSUE TITLE
Alternative use of MYSQL instead of PostgreSQL

### ISSUE THREAD

**Issue by MarcoAntonioValencia** [code-chat-br/whatsapp-api#92]
Hello, i wanted to know if there's anything particular that is being used from postgreSQL that does not exist in other sql db managers that could impede using others,  or is it posible to just switch for example to MySQL

Thank you.

**Comment by jrCleber** [comment]
The API works exclusively with the Postgres manager. However, Prisma ORM is very flexible, and you can easily change the [schema](https://github.com/code-chat-br/whatsapp-api/blob/main/prisma/schema.prisma) to MySQL by following the [Prisma documentation](https://www.prisma.io/docs/getting-started).
