### ISSUE TITLE
WebHook image is encrypted

### ISSUE THREAD

**Issue by JoaoNetoDev** [code-chat-br/whatsapp-api#96]
In WebHook I noticed that the image is encrypted... is there any procedure to decrypt it or to receive it in base64?

**Comment by JoaoNetoDev** [comment]
I discovered the "retrieverMediaMessage" route here, sorry!

**Comment by mrlazarias** [comment]
Como tu conseguiu fazer isso?

**Comment by paulowender** [comment]
Também gostaria de saber como estão utilizando o endpoint retrieveMediaMessage, pois não consigo decodar/exibir de maneira alguma os arquivos de midia

**Comment by mrlazarias** [comment]
Se quiser pode me mandar mensagem que te ajudo

> Também gostaria de saber como estão utilizando o endpoint retrieveMediaMessage, pois não consigo decodar/exibir de maneira alguma os arquivos de midia
